In [4]:
import torch
import numpy as np
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


Torch accept direct input or np array input
Use ones_like and rand_like will generate same shapte variables.

Use M to change cell into markdown, and Y to change markdown to code

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6887, 0.0819],
        [0.9361, 0.7859]]) 



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9881, 0.2126, 0.2788],
        [0.7735, 0.3249, 0.1859]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
tensor

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


tensor([[0.4436, 0.3759, 0.8317, 0.9253],
        [0.2453, 0.6435, 0.1243, 0.4459],
        [0.5616, 0.9595, 0.3338, 0.8770]])

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    print('CUDA work here.')
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")
else:
    print('No CUDA, work on CPU.')


CUDA work here.
Device tensor is stored on: cuda:0


In [20]:
# You can use tensor in standart array like operation
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)


First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
# and we can just cat tensors as normal array. dim=0 to cat vertical and dim=1 to horizontal.
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) # can just put output into y3 varibable, and print result.



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [29]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [32]:
# single element can use tensor.item() to change into float number.
# only single element tensor can do so.
agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.) <class 'torch.Tensor'>
12.0 <class 'float'>


In [33]:
#In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [47]:
#Tensors on the CPU can directly change into numpy array.
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
# they share same memory, so change one will affect another!
t.add_(1)
print(f"t add one is: {t}")
print(f"n affect by t operation too: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t add one is: tensor([2., 2., 2., 2., 2.])
n affect by t operation too: [2. 2. 2. 2. 2.]


In [51]:
# this only work on cpu, so data in cuda cannot do this.
t= t.to('cuda')
print(f'Store t in GPU: {t.device}')
try:
    n = t.numpy()
except TypeError:
    print(f'Not allowed to use on cuda.')
    t_cpu = t.cpu()
    n = t_cpu.numpy()
    print(f"n: {n}")

Store t in GPU: cuda:0
Not allowed to use on cuda.
n: [2. 2. 2. 2. 2.]


In [53]:
# Use torch.from_numpy() to change numpy array direct into torch tensor.
n = np.ones(5)
t = torch.from_numpy(n)
# still, change one will affect another.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
